### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by yuuhaixia** [liyihang1024/spinel_to_perovskite_TL#2]
Thank you very much to the author for his contribution and sharing, but when I run it, I get the following error？

Traceback (most recent call last):
  File "D:/jiashi/spinel_to_perovskite_TL-main/CE-features-generation/cif2TrainData_periodic_ABX.py", line 459, in <module>
    main("cif_conventional_unrelax")
  File "D:/jiashi/spinel_to_perovskite_TL-main/CE-features-generation/cif2TrainData_periodic_ABX.py", line 233, in main
    A_symbol_and_distance, B_symbol_and_distance, X_symbol_and_distance, A_col_count, B_col_count, X_col_count = getCifInfo(struc)
  File "D:/jiashi/spinel_to_perovskite_TL-main/CE-features-generation/cif2TrainData_periodic_ABX.py", line 66, in getCifInfo
    A_index = [list(site.values())[0] for site in unique_sites if list(site.keys())[0] == A][0] # Index of non equivalent A atoms
IndexError: list index out of range

![微信图片_20240520130556](https://github.com/liyihang1024/spinel_to_perovskite_TL/assets/104346921/1e480040-19cc-4b4a-b848-0386d0fe852f)

**Comment by liyihang1024** [comment]
Hello, thank you for following our work. This program is only applicable to spinel and perovskite crystal structures (containing only two types of cations and oxygen anions). When using it, the space group number and atomic number in the code need to be modified (for spinel, the space group and atomic number are 227 and 56, respectively, and for perovskite, they are 221 and 5). It is temporarily not applicable to other crystal structures.
***@***.***
***@***.***
---- Replied Message ----
From ***@***.***> Date 05/20/2024 13:06 To ***@***.***> Cc ***@***.***> Subject [liyihang1024/spinel_to_perovskite_TL] IndexError: list index out of range (Issue #2) 
Thank you very much to the author for his contribution and sharing, but when I run it, I get the following error？
Traceback (most recent call last):
File "D:/jiashi/spinel_to_perovskite_TL-main/CE-features-generation/cif2TrainData_periodic_ABX.py", line 459, in 
main("cif_conventional_unrelax")
File "D:/jiashi/spinel_to_perovskite_TL-main/CE-features-generation/cif2TrainData_periodic_ABX.py", line 233, in main
A_symbol_and_distance, B_symbol_and_distance, X_symbol_and_distance, A_col_count, B_col_count, X_col_count = getCifInfo(struc)
File "D:/jiashi/spinel_to_perovskite_TL-main/CE-features-generation/cif2TrainData_periodic_ABX.py", line 66, in getCifInfo
A_index = [list(site.values())[0] for site in unique_sites if list(site.keys())[0] == A][0] # Index of non equivalent A atoms
IndexError: list index out of range
_20240520130556.png (view on web)

**Comment by yuuhaixia** [comment]
Thank you very much for letting us know. I went ahead and ran it using the data you gave me as well as the code and it was not modified. But I am getting "IndexError: list index out of range". To make it work, I gave them a default value as shown below. However, now I am getting "FileNotFoundError: [Errno 2] No such file or directory: 'target.xlsx'". Where can I get this file from please, can you provide it to  @liyihang1024 

![微信图片_20240520223147](https://github.com/liyihang1024/spinel_to_perovskite_TL/assets/104346921/3a8979a8-e182-4f06-b04d-2eb1622f4f04)
